CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE ESTILO (
idEstilo TINYINT PRIMARY KEY IDENTITY (1,1),
nomeEstilo VARCHAR (20) NOT NULL
);

CREATE TABLE ARTISTA (
idArtista SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeArtista VARCHAR (20) NOT NULL
);

CREATE TABLE ALBUM (
idAlbum TINYINT PRIMARY KEY IDENTITY (1,1),
idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
nomeAlbum VARCHAR (20) NOT NULL,
duracao SMALLINT NOT NULL,
disponibilidade BIT NOT NULL
);

CREATE TABLE USUARIO (
idUsuario INT PRIMARY KEY IDENTITY (1,1),
nomeUsuario VARCHAR (20) NOT NULL,
emailUsuario VARCHAR (20) NOT NULL,
senhaUsuario VARCHAR (20) NOT NULL,
permissao BIT NOT NULL
);

CREATE TABLE ALBUMUSUARIO (
idA_Usuario INT PRIMARY KEY	IDENTITY (1,1),
idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
dataLancamento CHAR (10) NOT NULL	
);

CREATE TABLE ARTISTAALBUM (
idA_album TINYINT PRIMARY KEY IDENTITY (1,1),
idAlbum TINYINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
dataCriacao CHAR (10) NOT NULL
);

CREATE TABLE ALBUMESTILO (
idA_estilo INT PRIMARY KEY IDENTITY (1,1),
idAlbum TINYINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
idEstilo TINYINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
dataLancamento CHAR (10) NOT NULL
);